apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
    labels:
       tier: frontend
       app: nginx
spec:
  selector:
    matchLabels:
      env: production
  replicas: 1
  template:
      metadata:
        name: myapp
        labels:
          env: production
      spec:
        containers:
         - name: mycv
           image: 35428/mzakaria-web
