apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tier: frontend
  name: myapp-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    env: production
  type: LoadBalancer
